[package]
name = "test-api"
authors = ["Manuel Olguín Muñoz <manuel@olguinmunoz.xyz>"]
license = "Apache-2.0"
version = "0.0.1"
edition = "2021"
description = "A test API for programming exercises."
homepage = "https://github.com/molguin92/TestAPI"
repository = "https://github.com/molguin92/TestAPI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["tokio"] }
clap = { version = "4.4", features = ["derive", "env"] }
clap_derive = "4.4"
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_prometheus = "0.2"
simple_logger = "4.3"
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros"] }
jwt-simple = "0.12"
uuid = { version = "1.7.0", features = ["v4"] }
rand_derive2 = "0.1"
rand = "0.8"